kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: {{ NAME }}
  namespace: eessibasis
  labels:
    team: eessibasis
spec:
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: {{ SPRING_PROFILE }}
    - name: EUX_RELATERTE_RINASAKER_URL
      value: {{ INGRESS }}
  image: {{ IMAGE }}
  ingresses:
    - {{ INGRESS }}
  gcp:
    sqlInstances:
      - type: POSTGRES_14
        cascadingDelete: true
        databases:
          - name: db
            envVarPrefix:
              DATABASE
  liveness:
    path: /actuator/health
    port: 8080
    initialDelay: 20
    timeout: 70
  port: 8080
  prometheus:
    enabled: true
    path: /actuator/prometheus
  readiness:
    path: /actuator/health
    port: 8080
    initialDelay: 20
    timeout: 70
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 80
  resources:
    limits:
      cpu: "1"
      memory: 3072Mi
    requests:
      cpu: 200m
      memory: 2048Mi
  progressDeadlineSeconds: 120
  azure:
    application:
      enabled: true
      replyURLs:
        - "{{ INGRESS }}/callback"
