name: eux-relaterte-rinasaker
ingress: https://eux-relaterte-rinasaker.intern.nav.no
database.name: eux-relaterte-rinasaker-db
application:
  eux-neessi:
    name: eux-neessi
    namespace: eessibasis
cluster:
  fss: dev-fss
  gcp: dev-gcp
