datasource:
  hikari:
    jdbc-url: "jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_DATABASE}"
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    maximum-pool-size: 2
    minimum-idle: 1
    initialization-fail-timeout: 60000
