openapi: 3.0.3
info:
  title: Relaterte rinasaker API
  description: API for å behandle grupper av rina-saker
  contact:
    name: vegard.lundeberg.hillestad@nav.no
  version: v1
servers:
  - url: 'http://localhost:8080/api/v1'
tags:
  - name: Relaterte Rinasaker API
    description: API for å behandle grupper av relaterte rinasaker

paths:
  '/relaterterinasaker/søk':
    $ref: 'relaterte-rinasaker/operations_søk.yaml'
  '/relaterterinasaker':
    $ref: 'relaterte-rinasaker/operations_rot.yaml'
