openapi: 3.0.3
info:
  title: Rinasak API
  description: API for å behandle rina-saker
  contact:
    name: vegard.lundeberg.hillestad@nav.no
  version: v4
servers:
  - url: 'http://localhost:8080/api/v4'
tags:
  - name: Relaterte Rinasaker API
    description: API for å behandle rina-saker

paths:
  '/relaterterinasaker/searches':
    $ref: 'relaterte-rinasaker/operations_searches.yaml'
  '/relaterterinasaker':
    $ref: 'relaterte-rinasaker/operations_root.yaml'
