name: Build

on:
  push:
    branches: [ main ]
  pull_request:

env:
  DATABASE_HOST: localhost
  DATABASE_PORT: 5432
  DATABASE_DATABASE: postgres
  DATABASE_USERNAME: postgres
  DATABASE_PASSWORD: postgres
  READER_TOKEN: ${{ secrets.READER_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up java 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
          cache: 'maven'

      - name: Build and test
        run: >
          mvn clean install
          --settings ./.github/settings.xml
          --no-transfer-progress -B
