name: Deploy to q1
run-name: Deploy version ${{ github.event.inputs.version }} to NAIS, dev-gcp, q1

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'New version to deploy'
        required: true

env:
  APP_NAME: eux-relaterte-rinasaker
  IMAGE: ghcr.io/${{ github.repository }}/eux-relaterte-rinasaker
  READER_TOKEN: ${{ secrets.READER_TOKEN }}

jobs:
  deploy:
    name: 'Deploy to NAIS'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 'Calling deploy action (eessibasis namespace)'
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: .nais/nais.yaml
          VAR: image=${{ env.IMAGE }}:${{ github.event.inputs.version }}
          VARS: .nais/q1.yaml
          PRINT_PAYLOAD: true
