name: Deploy to production
run-name: Deploy version ${{ github.event.inputs.version }} to NAIS, prod-gcp, production

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'New version to deploy'
        required: true
      environment:
        description: 'Type prod'
        required: true

env:
  APP_NAME: eux-relaterte-rinasaker
  IMAGE: docker.pkg.github.com/${{ github.repository }}/eux-relaterte-rinasaker
  READER_TOKEN: ${{ secrets.READER_TOKEN }}

jobs:
  deploy:
    name: 'Deploy to NAIS'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 'Deploy to production'
        if: github.event.inputs.environment == 'prod'
        run: |
          echo "DOCKER_IMAGE=${{ env.IMAGE }}:${{ github.event.inputs.version }}" >> $GITHUB_ENV
          echo "CLUSTER=prod-gcp" >> $GITHUB_ENV
          echo "NAME=${{ env.APP_NAME }}" >> $GITHUB_ENV
          echo "INGRESS=https://eux-relaterte-rinasaker.intern.nav.no" >> $GITHUB_ENV
          echo "SERVICEUSER=/serviceuser/data/prod/srveux-app" >> $GITHUB_ENV
      - name: 'Calling deploy action (eessibasis namespace)'
        if: github.event.inputs.environment == 'prod'
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: ${{ env.CLUSTER }}
          RESOURCE: ./.nais/nais.yaml
          VAR: "SPRING_PROFILE=${{ env.SPRING_PROFILE }},\
            NAME=${{ env.NAME }},\
            IMAGE=${{ env.DOCKER_IMAGE }},\
            INGRESS=${{ env.INGRESS }},\
            SERVICEUSER=${{ env.SERVICEUSER }}"
          VARS: deploy/${{ env.VARS_FILE }}
          PRINT_PAYLOAD: true
