name: Deploy to q1
run-name: Deploy version ${{ github.event.inputs.version }} to NAIS, dev-gcp, q1

permissions:
  deployments: write
  packages: write
  contents: write
  id-token: write

on:
  workflow_dispatch:
    inputs:
      image:
        description: 'New image to deploy'
        required: true

env:
  APP_NAME: eux-relaterte-rinasaker
  IMAGE: ghcr.io/${{ github.repository }}/eux-relaterte-rinasaker
  READER_TOKEN: ${{ secrets.READER_TOKEN }}

jobs:
  deploy:
    name: 'Deploy to NAIS'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 'Calling deploy action (eessibasis namespace)'
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/nais.yaml
          VAR: image=${{ github.event.inputs.image }}
          VARS: .nais/q1.yaml
          PRINT_PAYLOAD: true
