name: Deploy to production
run-name: Deploy version ${{ github.event.inputs.version }} to NAIS, prod-gcp, production

permissions:
  deployments: write
  packages: write
  contents: write
  id-token: write

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'New version to deploy'
        required: true
      environment:
        description: 'Type prod'
        required: true

env:
  IMAGE: europe-north1-docker.pkg.dev/nais-management-233d/eessibasis/eux-relaterte-rinasaker
  READER_TOKEN: ${{ secrets.READER_TOKEN }}

jobs:
  deploy:
    name: 'Deploy to NAIS'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 'Calling deploy action (eessibasis namespace)'
        if: github.event.inputs.environment == 'prod'
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: .nais/nais.yaml
          VAR: "image=${{ env.IMAGE }}:${{ github.event.inputs.version }}"
          VARS: .nais/prod.yaml
          PRINT_PAYLOAD: true
