name: Deploy to production
run-name: Deploy version ${{ github.event.inputs.version }} to NAIS, prod-gcp, production

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'New version to deploy'
        required: true
      environment:
        description: 'Type prod'
        required: true

env:
  APP_NAME: eux-relaterte-rinasaker
  IMAGE: docker.pkg.github.com/${{ github.repository }}/eux-relaterte-rinasaker
  READER_TOKEN: ${{ secrets.READER_TOKEN }}

jobs:
  deploy:
    name: 'Deploy to NAIS'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 'Calling deploy action (eessibasis namespace)'
        if: github.event.inputs.environment == 'prod'
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: .nais/nais.yaml
          VAR: image=${{ needs.build.outputs.docker-image }}
          VARS: .nais/prod.yaml
          PRINT_PAYLOAD: true
